name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Verify API
        run: |-
          echo 'API_SUCCESS='$(curl https://gist.githubusercontent.com/will-r-chase/bd5c3be87e03a98cfa96284e3895c050/raw/642fb9bf80b4cd18844844ebca51c70d20d34520/test_abort.json | jq '.success') >> $GITHUB_ENV
      - name: Test env
        run: |
          echo ${{env.API_SUCCESS}}
      - name: Fetch latest data
        run: |
          [[ ${{env.API_SUCCESS}} == "true" ]] && curl 'https://gist.githubusercontent.com/will-r-chase/bd5c3be87e03a98cfa96284e3895c050/raw/642fb9bf80b4cd18844844ebca51c70d20d34520/test_abort.json' || echo "Not equal"
      - name: Commit and push if it change
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
